using System;
using System.Collections.Generic;
using System.Text;

namespace MonoGCDeadlockLib
{
    // NOT ACTUALLY AUTOGENERATED!
    public delegate void CallbackToCLRDelegate(string mesg);
}
